version: '2'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.development
    expose:
      - 8080
    environment:
      - VIRTUAL_HOST=tala.dev
    volumes:
      - .:/code
      - /code/node_modules

  api:
    build: ../tala-api/.
    command: npm run dev
    environment:
      - VIRTUAL_HOST=api.tala.dev
    volumes:
      - ../tala-api/.:/code
      - /code/node_modules
