version: '2'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.development
    depends_on:
      - proxy
    environment:
      - VIRTUAL_HOST=tala.dev # For nginx proxy
    volumes:
      - .:/code
      - /code/node_modules

  api:
    build: ../tala-api/.
    command: npm run dev
    depends_on:
      - proxy
    environment:
      - VIRTUAL_HOST=api.tala.dev # For nginx proxy
    volumes:
      - ../tala-api/.:/code
      - /code/node_modules

  proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
