version: '2'

services:
  web-dev:
    build:
      context: .
      dockerfile: Dockerfile.development
    expose:
      - 8080
    environment:
      - VIRTUAL_HOST=tala.dev
    volumes:
      - .:/code
      - /code/node_modules

  web:
    build: .
    environment:
      - VIRTUAL_HOST=staging.tala.dev
    expose:
      - 80
    volumes:
      - .:/code
      - /code/node_modules

  api:
    image: 'davidblurton/tala-api:latest'
    environment:
      - VIRTUAL_HOST=api.tala.dev

  proxy:
    image: 'dockercloud/haproxy:latest'
    links:
      - api
      - web
      - web-dev
    ports:
      - '80:80'
      - '443:443'
      - '1936:1936'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
